### ISSUE TITLE
Archive this project

### ISSUE THREAD

**Issue by quotidian-ennui** [adaptris/interlok-vertx#216]
- Archive this project
- There's no users
- In it's current form it's not really usable in production.
- It's already in the `com.adaptris.labs` maven group since 4.0 so it's classed as "experimental"
- https://github.com/adaptris/interlok-vertx/pull/211 broke it, and it's just going to cause ongoing toil with dependabot.

**Comment by sebastien-belin-adp** [comment]
adaptris/interlok-vertx ha been archived and remove from pipelines and release scripts.
